FROM node:18-alpine AS build

WORKDIR /var/www/frontend
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ ./
ENV VITE_API_URL=/graphql
RUN npm run build

FROM nginx:alpine
COPY --from=build /var/www/frontend/dist /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
